[package]
name = "bevy_mqtt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
websocket = ["rumqttc/websocket"]

[dependencies]
bevy = { version = "0.13.1", default-features = false }
rumqttc = "0.24.0"