[package]
name = "bevy_mqtt"
description = "A simple MQTT client for Bevy ECS"
version = "0.3.2"
edition = "2021"
readme = "README.md"
repository = "https://github.com/foxzool/bevy_mqtt"
authors = ["FoxZoOL <zhooul@gmail.com>"]
license = "MIT OR Apache-2.0"
categories = ["game-development", "network-programming"]
keywords = ["bevy", "mqtt", "plugin"]

[features]
websocket = ["rumqttc/websocket"]
proxy = ["rumqttc/proxy"]
native-tls = ["rumqttc/use-native-tls"]
rust-tls = ["rumqttc/use-rustls"]

[dependencies]
bevy_app = { version = "0.14.0" }
bevy_ecs = { version = "0.14.0" }
bevy_state = { version = "0.14.0" }
bevy_log = { version = "0.14.0" }
bevy_derive = { version = "0.14.0" }

rumqttc = { version = "0.24.0", features = ["url"] }
bevy-tokio-tasks = { version = "0.14.0" }
kanal = "0.1.0-pre8"
bytes = "1"
tokio = { version = "1", features = ["rt", "sync"] }
regex = { version = "1.10.6" }

[dev-dependencies]
bevy = { version = "0.14.2", default-features = false }
bincode = "1.3.3"
time = "0.3"
serde = { version = "1", features = ["derive"] }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tokio = { version = "1", features = ["rt-multi-thread"] }


[[example]]
name = "pub_and_sub"
path = "examples/pub_and_sub.rs"

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["websocket"]

