[package]
name = "bevy_mqtt"
description = "A simple MQTT client for Bevy"
version = "0.2.0"
edition = "2021"
readme = "README.md"
repository = "https://github.com/foxzool/bevy_mqtt"
authors = ["FoxZoOL <zhooul@gmail.com>"]
license = "MIT OR Apache-2.0"
categories = ["game-development", "network-programming"]
keywords = ["bevy", "mqtt", "plugin"]

[features]
websocket = ["rumqttc/websocket"]
proxy = ["rumqttc/proxy"]

[dependencies]
bevy = { version = "0.14.0", default-features = false }
rumqttc = "0.24.0"
tokio = { version = "1.36.0", features = ["sync", "rt-multi-thread", "macros"] }
time = "0.3.34"

[dev-dependencies]
bincode = "1.3.3"
serde = { version = "1", features = ["derive"] }

[[example]]
name = "websocket"
path = "examples/websocket.rs"
required-features = ["websocket"]